name: Check Upgradable Version
description: Check the latest version of package.json then compare with the latest release on GitHub
author: Akhmad Thoriq
inputs:
  owner:
    description: The name of the owner of the repo. Used to identify the owner of the repository.
    required: false
  repo:
    description: The name of the repository. Used to identify the repository on which to release.
    required: false
  package_json_path:
    description: The path to the package.json file. Can be used for monorepo. Example packages/app/
    required: false
    default: '.'
  debug:
    description: Show output for debugging
    required: false
    default: 'false'
  version_prefix:
    description: The prefix used in version tag (e.g., 'v')
    required: false
  include_prefix:
    description: Whether to include the version_prefix in the to_version and from_version outputs
    required: false
    default: 'false'
  prerelease_suffix_regex:
    description: Regex to match prerelease suffixes
    required: false
    default: '-(alpha|beta|rc)\.'
outputs:
  from_version:
    description: The latest version of the release
  to_version:
    description: The current version of the package.json
  is_upgradable:
    description: Is upgradable
  is_prerelease:
    description: Whether the current version is a prerelease
runs:
  using: node20
  main: dist/index.js
branding:
  icon: tag
  color: blue
